### ISSUE TITLE
Error when executing pytests

### ISSUE THREAD

**Issue by mianasbat** [SciKit-Surgery/scikit-surgeryfredmatplotlib#13]
According to the readme file, I cloned the repo and run the pytest and I got the following error (screenshots attached). I am on Mac and Python version is 3.7.3 and pytest library is installed.
To reproduce the error
```
git clone https://github.com/UCL/scikit-surgeryfred
cd scikit-surgeryfred
python -m pytest
```
Pytest version
```
$ pip list | grep pytest
pytest                             4.3.1   
pytest-arraydiff                   0.3     
pytest-astropy                     0.5.0   
pytest-doctestplus                 0.3.0   
pytest-openfiles                   0.3.2   
pytest-remotedata                  0.3.1
```

<img width="1280" alt="Screenshot 2020-06-25 at 09 19 18" src="https://user-images.githubusercontent.com/2621305/85684748-4d025600-b6c6-11ea-9b8a-474c73fca23a.png">

**Comment by thompson318** [comment]
It needs scikit-surgerycore>0.6.5. Have you updated your surgery core or can you use tox?

**Comment by mianasbat** [comment]
Spot on Steve!

#### For records:
I checked scikit-surgerycore version on my system and I was having scikit-surgerycore 0.6.5. I upgraded scikit-surgerycore library and now the error disappeared. 

Here are the steps:

To check the version of scikit-surgerycore I run the command in terminal
```
pip list | grep scikit-surgerycore
```
To upgrade the scikit-surgerycore version to the latest, I run the command
```
pip install --upgrade scikit-surgerycore
```
To verify that the package is updated to the latest one (0.6.6), I run once again
```
pip list | grep scikit-surgerycore
```
