### ISSUE TITLE
Unable to install the library

### ISSUE THREAD

**Issue by mianasbat** [SciKit-Surgery/scikit-surgeryfredmatplotlib#14]
According to the readme file, I tried to install the package on my mac but I got an error `failed with error code 128 in None`. Screenshot attached.
Steps to reproduce is
```
Open terminal on mac
$ pip install git+https://github.com/UCL/FiducialRegistrationEducationalDemonstration

```
Here is the screenshot and error details.

<img width="1280" alt="Screenshot 2020-06-25 at 09 30 48" src="https://user-images.githubusercontent.com/2621305/85685375-e6ca0300-b6c6-11ea-9c03-176371de09aa.png">

**Comment by thompson318** [comment]
The readme is wrong, it should say:
pip install git+https://github.com/UCL/scikit-surgeryfred
please can you update it?

**Comment by mianasbat** [comment]
That worked like a charm!
I am updating the read me file.
#### For records
Open terminal and run the command
```
pip install git+https://github.com/UCL/scikit-surgeryfred
```
To check the version and verify the library is installed
```
pip list | grep scikit-surgeryfred
```
