### ISSUE TITLE
Error when executing the library

### ISSUE THREAD

**Issue by mianasbat** [SciKit-Surgery/scikit-surgeryfredmatplotlib#19]
I believe I got another error related to logging module when executing the `sksurgeryfred.py`.  The steps to reproduce on MAC are
```
git clone https://github.com/UCL/scikit-surgeryfred
cd scikit-surgeryfred
python sksurgeryfred
```
The error screenshot is
<img width="1754" alt="Screenshot 2020-06-25 at 11 08 54" src="https://user-images.githubusercontent.com/2621305/85700669-8477ff00-b6d4-11ea-93e6-2d7680266c80.png">

**Comment by mianasbat** [comment]
Just to update, this is the `sksurgeryfred` which got installed in my system. 
If I do `python ./sksurgeryfred.py` then it seems to run.

**Comment by thompson318** [comment]
This looks weird, and I can't replicate it. Do you know what version of scikit-surgeryFRED you had installed on your system at the time?

**Comment by thompson318** [comment]
Cannot replicate, closing
