### ISSUE TITLE
It would be nice to have a sample image in tests directory.

### ISSUE THREAD

**Issue by mianasbat** [SciKit-Surgery/scikit-surgeryfredmatplotlib#20]
I was able to clone the repo and run it fine. But I got the error message to supply the image argument, which is not an error basically. Wouldn't it be nice to provide a sample image in the `scikit-surgeryfred/tests` directory so that users could run it for testing.
To reproduce 
```
git clone https://github.com/UCL/scikit-surgeryfred
cd scikit-surgeryfred
python sksurgeryfred.py
```
The screenshot of missing argument error is 

<img width="881" alt="Screenshot 2020-06-25 at 11 24 54" src="https://user-images.githubusercontent.com/2621305/85702741-9d81af80-b6d6-11ea-9eb6-3b52a9859e51.png">

So if we have an image in tests then users could do
```
python sksurgeryfred.py -image tests/image
```

**Comment by thompson318** [comment]
There should be a sample image in the data directory data/brain512.png

**Comment by mianasbat** [comment]
It is good to hear that but I am getting error for the image you mentioned unless I am doing something wrong.
Here is the error
<img width="1144" alt="Screenshot 2020-06-25 at 12 10 08" src="https://user-images.githubusercontent.com/2621305/85709338-1126bb00-b6dd-11ea-943c-5a808e7f7b80.png">

**Comment by thompson318** [comment]
like this

python sksurgery.py data/brain512.png

sorry I know it could be clearer.

**Comment by mianasbat** [comment]
Thanks Steve for the prompt reply. 
I believe you mean `python sksurgeryfred.py data/brain512.png`

I tried it but after flashing a small python window in the taskbar I got an error.
```
python sksurgeryfred.py data/brain512.png
```
<img width="1714" alt="Screenshot 2020-06-25 at 12 20 06" src="https://user-images.githubusercontent.com/2621305/85710866-9d85ad80-b6de-11ea-9ea8-c33cf26a32c9.png">

**Comment by thompson318** [comment]
That's something in scipy. Can you please let me know what version of scipy you've got?

**Comment by mianasbat** [comment]
I have `Scipy 1.2.1`.

**Comment by thompson318** [comment]
Sorry, I meant scikit-image version

**Comment by mianasbat** [comment]
I have scikit-image 0.14.2

**Comment by thompson318** [comment]
It needs a newer version of scikit-image. 0.16.x should be fine. I'll update requirements.txt and setup.py to specify minimum version of scikit-image. Thanks.

**Comment by mianasbat** [comment]
Amazing! it is working now. Thanks!

#### For records
After I updated scikit-image to the latest version `0.17.2` using the following command, it is working now.
```
pip install --upgrade scikit-image
```
To verify the update
```
pip list | grep scikit-image
```
